# -*- coding: utf-8 -*-


names_lgb_20190522_3 = [
    'price',
    'price_rank',
    'price_rank_first',
    'price_rank_ratio',
    'price_rank_first_ratio',
    '2 star',
    '3 star',
    '4 star',
    'accessible hotel',
    'accessible parking',
    'air conditioning',
    'airport shuttle',
    'balcony',
    'bathtub',
    'beach',
    'bed & breakfast',
    'bike rental',
    'business centre',
    'business hotel',
    'cable tv',
    'car park',
    'central heating',
    'computer with internet',
    'concierge',
    'conference rooms',
    'cosmetic mirror',
    'cot',
    'country hotel',
    'deck chairs',
    'desk',
    'electric kettle',
    'excellent rating',
    'express check-in / check-out',
    'family friendly',
    'fan',
    'fitness',
    'flatscreen tv',
    'free wifi (combined)',
    'free wifi (public areas)',
    'free wifi (rooms)',
    'fridge',
    'from 2 stars',
    'from 3 stars',
    'from 4 stars',
    'gay-friendly',
    'golf course',
    'good rating',
    'gym',
    'hairdryer',
    'hiking trail',
    'horse riding',
    'hotel',
    'hotel bar',
    'house / apartment',
    'ironing board',
    'jacuzzi (hotel)',
    'large groups',
    'laundry service',
    'lift',
    'luxury hotel',
    'massage',
    'microwave',
    'non-smoking rooms',
    'openable windows',
    'pet friendly',
    'playground',
    'pool table',
    'porter',
    'radio',
    'reception (24/7)',
    'restaurant',
    'romantic',
    'room service',
    'safe (hotel)',
    'safe (rooms)',
    'satellite tv',
    'satisfactory rating',
    'sauna',
    'self catering',
    'shower',
    'singles',
    'sitting area (rooms)',
    'sun umbrellas',
    'swimming pool (combined filter)',
    'swimming pool (outdoor)',
    'telephone',
    'television',
    'tennis court',
    'terrace (hotel)',
    'very good rating',
    'washing machine',
    'wheelchair accessible',
    'wifi (public areas)',
    'wifi (rooms)',
    'item_interaction_count',
    'item_interaction_session_count',
    'item_interaction_user_count',
    'item_interaction_item_image_count',
    'item_interaction_item_image_session_count',
    'item_interaction_item_image_user_count',
    'item_interaction_item_info_count',
    'item_interaction_item_info_session_count',
    'item_interaction_item_info_user_count',
    'item_interaction_item_rating_count',
    'item_interaction_item_rating_session_count',
    'item_interaction_item_rating_user_count',
    'item_interaction_item_deals_count',
    'item_interaction_item_deals_session_count',
    'item_interaction_item_deals_user_count',
    'item_search_for_item_count',
    'item_search_for_item_session_count',
    'item_search_for_item_user_count',
    'item_exposure_count',
    'item_exposure_session_count',
    'item_exposure_user_count',
    'item_exposure_count_top_3',
    'item_exposure_session_count_top_3',
    'item_exposure_user_count_top_3',
    'item_exposure_count_top_5',
    'item_exposure_session_count_top_5',
    'item_exposure_user_count_top_5',
    'item_exposure_count_top_10',
    'item_exposure_session_count_top_10',
    'item_exposure_user_count_top_10',
    'hour',
    'dayofweek',
    'step',
    'platform_le',
    'city_le',
    'country_le',
    'device_le',
    'session_action_type_first_le',
    'session_action_type_last_le',
    'session_interaction_item_count',
    'session_ts_all_imp',
    'session_step_all_imp',
    'session_interaction_item_price_min',
    'session_interaction_item_price_max',
    'session_interaction_item_price_mean',
    'session_interaction_item_price_std',
    'session_interaction_item_price_min_div',
    'session_interaction_item_price_max_div',
    'session_interaction_item_price_mean_div',
    'filter_Sort By Distance',
    'filter_Sort By Popularity',
    'filter_Sort By Rating',
    'filter_Sort by Price',
    'filter_Satisfactory Rating',
    'filter_Very Good Rating',
    'filter_Focus on Distance',
    'filter_Good Rating',
    'session_impressions_eq_last',
    'session_impressions_eq_last_imp',
    'session_item_first',
    'session_item_last',
    'session_item_interaction_item_image_count',
    'session_item_interaction_item_info_count',
    'session_item_interaction_item_rating_count',
    'session_item_interaction_item_deals_count',
    'session_item_search_for_item_count',
    'session_item_clickout_item_count',
    'session_item_interaction_count',
    'item_rank',
    'item_total',
    'item_rank_ratio',
    'session_item_first_interaction_step_diff_target',
    'session_item_first_interaction_timestamp_diff_target',
    'session_item_last_interaction_step_diff_target',
    'session_item_last_interaction_timestamp_diff_target',
    'session_item_first_interaction_item_image_step_diff_target',
    'session_item_first_interaction_item_image_timestamp_diff_target',
    'session_item_last_interaction_item_image_step_diff_target',
    'session_item_last_interaction_item_image_timestamp_diff_target',
    'session_item_first_interaction_item_info_step_diff_target',
    'session_item_first_interaction_item_info_timestamp_diff_target',
    'session_item_last_interaction_item_info_step_diff_target',
    'session_item_last_interaction_item_info_timestamp_diff_target',
    'session_item_first_interaction_item_rating_step_diff_target',
    'session_item_first_interaction_item_rating_timestamp_diff_target',
    'session_item_last_interaction_item_rating_step_diff_target',
    'session_item_last_interaction_item_rating_timestamp_diff_target',
    'session_item_first_interaction_item_deals_step_diff_target',
    'session_item_first_interaction_item_deals_timestamp_diff_target',
    'session_item_last_interaction_item_deals_step_diff_target',
    'session_item_last_interaction_item_deals_timestamp_diff_target',
    'session_item_first_search_for_item_step_diff_target',
    'session_item_first_search_for_item_timestamp_diff_target',
    'session_item_last_search_for_item_step_diff_target',
    'session_item_last_search_for_item_timestamp_diff_target',
    'session_item_first_clickout_item_step_diff_target',
    'session_item_first_clickout_item_timestamp_diff_target',
    'session_item_last_clickout_item_step_diff_target',
    'session_item_last_clickout_item_timestamp_diff_target',
    'session_last_interaction_item_index_diff',
    'session_last_interaction_item_index_diff_gt_0',
    'session_last_interaction_item_index_diff_gte_0',
    'session_item_price_imp_price_first_div',
    'session_item_price_imp_price_min_div',
    'session_item_price_imp_price_top_3_min_div',
    'session_item_price_imp_price_top_5_min_div',
    'session_item_price_imp_price_top_10_min_div'
]


names_lgb_20190522_3_top_30 = [
    'session_item_last',
    'item_rank_ratio',
    'item_rank',
    'session_item_last_interaction_step_diff_target',
    'session_last_interaction_item_index_diff',
    'session_item_last_interaction_timestamp_diff_target',
    'step',
    'price_rank_first',
    'session_ts_all_imp',
    'session_last_interaction_item_index_diff_gt_0',
    'session_action_type_last_le',
    'session_item_first_interaction_step_diff_target',
    'session_interaction_item_price_mean_div',
    'session_item_price_imp_price_top_3_min_div',
    'item_total',
    'price_rank',
    'session_step_all_imp',
    'session_item_interaction_count',
    'session_interaction_item_price_max_div',
    'session_item_first_clickout_item_timestamp_diff_target',
    'session_interaction_item_price_min_div',
    'session_item_price_imp_price_first_div',
    'session_item_price_imp_price_min_div',
    'item_exposure_user_count_top_3',
    'device_le',
    'session_impressions_eq_last_imp',
    'item_exposure_count_top_3',
    'session_action_type_first_le',
    'session_interaction_item_count',
    'session_item_first'
]

names_lgb_20190522_3_top_100 = [
    'price',
    'price_rank',
    'price_rank_first',
    'price_rank_ratio',
    'price_rank_first_ratio',
    'beach',
    'car park',
    'from 4 stars',
    'hotel',
    'jacuzzi (hotel)',
    'lift',
    'massage',
    'satisfactory rating',
    'very good rating',
    'item_interaction_count',
    'item_interaction_session_count',
    'item_interaction_user_count',
    'item_interaction_item_image_count',
    'item_interaction_item_image_session_count',
    'item_interaction_item_image_user_count',
    'item_interaction_item_info_count',
    'item_interaction_item_info_session_count',
    'item_interaction_item_info_user_count',
    'item_interaction_item_rating_count',
    'item_interaction_item_rating_session_count',
    'item_interaction_item_rating_user_count',
    'item_interaction_item_deals_count',
    'item_interaction_item_deals_session_count',
    'item_interaction_item_deals_user_count',
    'item_search_for_item_count',
    'item_search_for_item_session_count',
    'item_search_for_item_user_count',
    'item_exposure_count',
    'item_exposure_session_count',
    'item_exposure_user_count',
    'item_exposure_count_top_3',
    'item_exposure_session_count_top_3',
    'item_exposure_user_count_top_3',
    'item_exposure_count_top_5',
    'item_exposure_session_count_top_5',
    'item_exposure_user_count_top_5',
    'item_exposure_count_top_10',
    'item_exposure_session_count_top_10',
    'item_exposure_user_count_top_10',
    'hour',
    'step',
    'platform_le',
    'city_le',
    'country_le',
    'device_le',
    'session_action_type_first_le',
    'session_action_type_last_le',
    'session_interaction_item_count',
    'session_ts_all_imp',
    'session_step_all_imp',
    'session_interaction_item_price_min',
    'session_interaction_item_price_max',
    'session_interaction_item_price_mean',
    'session_interaction_item_price_std',
    'session_interaction_item_price_min_div',
    'session_interaction_item_price_max_div',
    'session_interaction_item_price_mean_div',
    'filter_Sort by Price',
    'session_impressions_eq_last',
    'session_impressions_eq_last_imp',
    'session_item_first',
    'session_item_last',
    'session_item_interaction_item_image_count',
    'session_item_search_for_item_count',
    'session_item_clickout_item_count',
    'session_item_interaction_count',
    'item_rank',
    'item_total',
    'item_rank_ratio',
    'session_item_first_interaction_step_diff_target',
    'session_item_first_interaction_timestamp_diff_target',
    'session_item_last_interaction_step_diff_target',
    'session_item_last_interaction_timestamp_diff_target',
    'session_item_first_interaction_item_image_step_diff_target',
    'session_item_first_interaction_item_image_timestamp_diff_target',
    'session_item_last_interaction_item_image_step_diff_target',
    'session_item_last_interaction_item_image_timestamp_diff_target',
    'session_item_last_interaction_item_info_step_diff_target',
    'session_item_last_interaction_item_info_timestamp_diff_target',
    'session_item_first_search_for_item_step_diff_target',
    'session_item_first_search_for_item_timestamp_diff_target',
    'session_item_last_search_for_item_step_diff_target',
    'session_item_last_search_for_item_timestamp_diff_target',
    'session_item_first_clickout_item_step_diff_target',
    'session_item_first_clickout_item_timestamp_diff_target',
    'session_item_last_clickout_item_step_diff_target',
    'session_item_last_clickout_item_timestamp_diff_target',
    'session_last_interaction_item_index_diff',
    'session_last_interaction_item_index_diff_gt_0',
    'session_last_interaction_item_index_diff_gte_0',
    'session_item_price_imp_price_first_div',
    'session_item_price_imp_price_min_div',
    'session_item_price_imp_price_top_3_min_div',
    'session_item_price_imp_price_top_5_min_div',
    'session_item_price_imp_price_top_10_min_div',
]


names_lgb_20190622_2 = [
    'm1_price',
    'm1_price_rank',
    'm1_price_rank_first',
    'm1_price_rank_ratio',
    'm1_price_rank_first_ratio',
    'm1_beach',
    'm1_car park',
    'm1_from 4 stars',
    'm1_hotel',
    'm1_jacuzzi (hotel)',
    'm1_lift',
    'm1_massage',
    'm1_satisfactory rating',
    'm1_very good rating',
    'm1_item_interaction_count',
    'm1_item_interaction_session_count',
    'm1_item_interaction_user_count',
    'm1_item_interaction_item_image_count',
    'm1_item_interaction_item_image_session_count',
    'm1_item_interaction_item_image_user_count',
    'm1_item_interaction_item_info_count',
    'm1_item_interaction_item_info_session_count',
    'm1_item_interaction_item_info_user_count',
    'm1_item_interaction_item_rating_count',
    'm1_item_interaction_item_rating_session_count',
    'm1_item_interaction_item_rating_user_count',
    'm1_item_interaction_item_deals_count',
    'm1_item_interaction_item_deals_session_count',
    'm1_item_interaction_item_deals_user_count',
    'm1_item_search_for_item_count',
    'm1_item_search_for_item_session_count',
    'm1_item_search_for_item_user_count',
    'm1_item_exposure_count',
    'm1_item_exposure_session_count',
    'm1_item_exposure_user_count',
    'm1_item_exposure_count_top_3',
    'm1_item_exposure_session_count_top_3',
    'm1_item_exposure_user_count_top_3',
    'm1_item_exposure_count_top_5',
    'm1_item_exposure_session_count_top_5',
    'm1_item_exposure_user_count_top_5',
    'm1_item_exposure_count_top_10',
    'm1_item_exposure_session_count_top_10',
    'm1_item_exposure_user_count_top_10',
    'm1_hour',
    'm1_step',
    'm1_platform_le',
    'm1_city_le',
    'm1_country_le',
    'm1_device_le',
    'm1_session_action_type_first_le',
    'm1_session_action_type_last_le',
    'm1_session_interaction_item_count',
    'm1_session_ts_all_imp',
    'm1_session_step_all_imp',
    'm1_session_interaction_item_price_min',
    'm1_session_interaction_item_price_max',
    'm1_session_interaction_item_price_mean',
    'm1_session_interaction_item_price_std',
    'm1_session_interaction_item_price_min_div',
    'm1_session_interaction_item_price_max_div',
    'm1_session_interaction_item_price_mean_div',
    'm1_filter_Sort by Price',
    'm1_session_impressions_eq_last',
    'm1_session_impressions_eq_last_imp',
    'm1_session_item_first',
    'm1_session_item_last',
    'm1_session_item_interaction_item_image_count',
    'm1_session_item_search_for_item_count',
    'm1_session_item_clickout_item_count',
    'm1_session_item_interaction_count',
    'm1_item_rank',
    'm1_item_total',
    'm1_item_rank_ratio',
    'm1_session_item_first_interaction_step_diff_target',
    'm1_session_item_first_interaction_timestamp_diff_target',
    'm1_session_item_last_interaction_step_diff_target',
    'm1_session_item_last_interaction_timestamp_diff_target',
    'm1_session_item_first_interaction_item_image_step_diff_target',
    'm1_session_item_first_interaction_item_image_timestamp_diff_target',
    'm1_session_item_last_interaction_item_image_step_diff_target',
    'm1_session_item_last_interaction_item_image_timestamp_diff_target',
    'm1_session_item_last_interaction_item_info_step_diff_target',
    'm1_session_item_last_interaction_item_info_timestamp_diff_target',
    'm1_session_item_first_search_for_item_step_diff_target',
    'm1_session_item_first_search_for_item_timestamp_diff_target',
    'm1_session_item_last_search_for_item_step_diff_target',
    'm1_session_item_last_search_for_item_timestamp_diff_target',
    'm1_session_item_first_clickout_item_step_diff_target',
    'm1_session_item_first_clickout_item_timestamp_diff_target',
    'm1_session_item_last_clickout_item_step_diff_target',
    'm1_session_item_last_clickout_item_timestamp_diff_target',
    'm1_session_last_interaction_item_index_diff',
    'm1_session_last_interaction_item_index_diff_gt_0',
    'm1_session_last_interaction_item_index_diff_gte_0',
    'm1_session_item_price_imp_price_first_div',
    'm1_session_item_price_imp_price_min_div',
    'm1_session_item_price_imp_price_top_3_min_div',
    'm1_session_item_price_imp_price_top_5_min_div',
    'm1_session_item_price_imp_price_top_10_min_div',
    'item_id_impression_prev_item_meta_cos',
    'item_id_impression_prev_co_appearence_interaction_count',
    'item_id_impression_prev_co_appearence_impression_count',
    'item_id_impression_prev_similarity_wv_impression',
    'item_id_impression_prev_similarity_wv_interaction',
    'item_id_impression_first_item_meta_cos',
    'item_id_impression_first_co_appearence_interaction_count',
    'item_id_impression_first_co_appearence_impression_count',
    'item_id_impression_first_similarity_wv_impression',
    'item_id_impression_first_similarity_wv_interaction',
    'item_id_interaction_last_item_meta_cos',
    'item_id_interaction_last_co_appearence_interaction_count',
    'item_id_interaction_last_co_appearence_impression_count',
    'item_id_interaction_last_similarity_wv_impression',
    'item_id_interaction_last_similarity_wv_interaction',
    'item_id_interaction_most_item_meta_cos',
    'item_id_interaction_most_co_appearence_interaction_count',
    'item_id_interaction_most_co_appearence_impression_count',
    'item_id_interaction_most_similarity_wv_impression',
    'item_id_interaction_most_similarity_wv_interaction',
    'item_id_interaction_last_similarity_wv_impression_rank',
    'item_id_impression_prev_item_meta_cos_rank',
    'item_id_impression_prev_co_appearence_impression_count_rank',
    'item_id_impression_first_co_appearence_interaction_count_rank',
    'item_id_impression_first_co_appearence_impression_count_rank',
    'item_id_interaction_last_co_appearence_impression_count_rank',
    'item_id_interaction_last_co_appearence_interaction_count_rank'
]


names_lgb_20190624_1 = [
    'm1_price_rank',
    'm1_price_rank_first',
    'm1_item_exposure_count_top_3',
    'm1_item_exposure_user_count_top_3',
    'm1_step',
    'm1_device_le',
    'm1_session_action_type_first_le',
    'm1_session_action_type_last_le',
    'm1_session_interaction_item_count',
    'm1_session_ts_all_imp',
    'm1_session_step_all_imp',
    'm1_session_interaction_item_price_min_div',
    'm1_session_interaction_item_price_max_div',
    'm1_session_interaction_item_price_mean_div',
    'm1_session_impressions_eq_last_imp',
    'm1_session_item_first',
    'm1_session_item_last',
    'm1_session_item_interaction_count',
    'm1_item_rank',
    'm1_item_total',
    'm1_item_rank_ratio',
    'm1_session_item_first_interaction_step_diff_target',
    'm1_session_item_last_interaction_step_diff_target',
    'm1_session_item_last_interaction_timestamp_diff_target',
    'm1_session_item_first_clickout_item_timestamp_diff_target',
    'm1_session_last_interaction_item_index_diff',
    'm1_session_last_interaction_item_index_diff_gt_0',
    'm1_session_item_price_imp_price_first_div',
    'm1_session_item_price_imp_price_min_div',
    'm1_session_item_price_imp_price_top_3_min_div',
    'm3_session_id_by_last_ts_sub_max_rank',
    'm3_impr_rank',
    'm3_cur_ts_sub_last',
    'm3_last_act_gap',
    'm3_last_item_rank_diff',
    'm3_last_ts_sub_max',
    'm3_session_id_by_prices_rank',
    'm3_ctr',
    'm3_last_item_price_div',
    'm3_item_last_act',
    'm3_nb_left',
    'm3_sid_last_act',
    'm3_price_left_div',
    'm3_session_id_impressions_by_impr_rank_min',
    'm3_search for item_item_cnt',
    'm3_price_div',
    'm3_user_item_last_act',
    'm3_session_id_by_prices_count',
    'm3_interaction item image_item_cnt',
    'm3_item_rank_sub_median',
    'm3_sid_search for item',
    'm3_sid_interaction item image',
    'm3_item_all_impr',
    'm3_item_sid_impr_cnt',
    'm3_price_right_div',
    'm3_device',
    'm3_item_sid_clk_cnt',
    'm3_price_sub',
    'm3_nb_right',
    'm3_item_price_div_median',
    'm2_impr_rank',
    'm2_ts_sub_prev',
    'm2_abs_impr_rank_sub_lastest_item-impr_rank',
    'm2_impr_rank_sub_lastest_item-impr_rank',
    'm2_nearest_step_delta',
    'm2_prices_div_active_items-session_id_by_prices_median-v2',
    'm2_price_rank',
    'm2_act_pre1',
    'm2_lastest_item-impr_rank',
    'm2_impr_rank_sub_impressions_by_impr_rank_median',
    'm2_price_div',
    'm2_session_act_sum',
    'm2_prices_div_active_items-session_id_by_prices_median',
    'm2_impressions_by_hist_interaction item info_sum',
    'm2_impressions_by_hist_interaction item image_sum',
    'm2_impressions_by_hist_clickout item_sum',
    'm2_session_id_by_prices_count',
    'm2_impressions_target',
    'm2_impressions_active_ratio',
    'm2_price_div_impr_rank_1_price',
    'm2_impressions_target_sub_session_median',
    'm2_impressions_target_sub_session_max',
    'm2_session_hist_clickout item',
    'm2_device',
    'm2_impr_rank_sub_session_id_by_impr_rank_median',
    'm2_session_hist_interaction item image',
    'm2_impr_rank_1_impressions_target',
    'm2_impr_rank_sub_session_id_by_impr_rank_max',
    'm2_impr_rank_sub_session_id_by_impr_rank_min',
    'm2_current_filters',
    'item_id_impression_prev_item_meta_cos',
    'item_id_impression_prev_co_appearence_interaction_count',
    'item_id_impression_prev_co_appearence_impression_count',
    'item_id_impression_prev_similarity_wv_impression',
    'item_id_impression_prev_similarity_wv_interaction',
    'item_id_impression_first_item_meta_cos',
    'item_id_impression_first_co_appearence_interaction_count',
    'item_id_impression_first_co_appearence_impression_count',
    'item_id_impression_first_similarity_wv_impression',
    'item_id_impression_first_similarity_wv_interaction',
    'item_id_interaction_last_item_meta_cos',
    'item_id_interaction_last_co_appearence_interaction_count',
    'item_id_interaction_last_co_appearence_impression_count',
    'item_id_interaction_last_similarity_wv_impression',
    'item_id_interaction_last_similarity_wv_interaction',
    'item_id_interaction_most_item_meta_cos',
    'item_id_interaction_most_co_appearence_interaction_count',
    'item_id_interaction_most_co_appearence_impression_count',
    'item_id_interaction_most_similarity_wv_impression',
    'item_id_interaction_most_similarity_wv_interaction',
    'item_id_interaction_last_similarity_wv_impression_rank',
    'item_id_impression_prev_item_meta_cos_rank',
    'item_id_impression_prev_co_appearence_impression_count_rank',
    'item_id_impression_first_co_appearence_interaction_count_rank',
    'item_id_impression_first_co_appearence_impression_count_rank',
    'item_id_interaction_last_co_appearence_impression_count_rank',
    'item_id_interaction_last_co_appearence_interaction_count_rank',
]


names_lgb_20190626_2 = [
    'm1_price_rank',
    'm1_price_rank_first',
    'm1_item_exposure_count_top_3',
    'm1_item_exposure_user_count_top_3',
    'm1_step',
    'm1_device_le',
    'm1_session_action_type_first_le',
    'm1_session_action_type_last_le',
    'm1_session_interaction_item_count',
    'm1_session_ts_all_imp',
    'm1_session_step_all_imp',
    'm1_session_interaction_item_price_min_div',
    'm1_session_interaction_item_price_max_div',
    'm1_session_interaction_item_price_mean_div',
    'm1_session_impressions_eq_last_imp',
    'm1_session_item_first',
    'm1_session_item_last',
    'm1_session_item_interaction_count',
    'm1_item_rank',
    'm1_item_total',
    'm1_item_rank_ratio',
    'm1_session_item_first_interaction_step_diff_target',
    'm1_session_item_last_interaction_step_diff_target',
    'm1_session_item_last_interaction_timestamp_diff_target',
    'm1_session_item_first_clickout_item_timestamp_diff_target',
    'm1_session_last_interaction_item_index_diff',
    'm1_session_last_interaction_item_index_diff_gt_0',
    'm1_session_item_price_imp_price_first_div',
    'm1_session_item_price_imp_price_min_div',
    'm1_session_item_price_imp_price_top_3_min_div',
    'm3_session_id_by_last_ts_sub_max_rank',
    'm3_impr_rank',
    'm3_cur_ts_sub_last',
    'm3_last_act_gap',
    'm3_last_item_rank_diff',
    'm3_last_ts_sub_max',
    'm3_session_id_by_prices_rank',
    'm3_ctr',
    'm3_last_item_price_div',
    'm3_item_last_act',
    'm3_nb_left',
    'm3_sid_last_act',
    'm3_price_left_div',
    'm3_session_id_impressions_by_impr_rank_min',
    'm3_search for item_item_cnt',
    'm3_price_div',
    'm3_user_item_last_act',
    'm3_session_id_by_prices_count',
    'm3_interaction item image_item_cnt',
    'm3_item_rank_sub_median',
    'm3_sid_search for item',
    'm3_sid_interaction item image',
    'm3_item_all_impr',
    'm3_item_sid_impr_cnt',
    'm3_price_right_div',
    'm3_device',
    'm3_item_sid_clk_cnt',
    'm3_price_sub',
    'm3_nb_right',
    'm3_item_price_div_median',
    'm2_impr_rank',
    'm2_ts_sub_prev',
    'm2_abs_impr_rank_sub_lastest_item-impr_rank',
    'm2_impr_rank_sub_lastest_item-impr_rank',
    'm2_nearest_step_delta',
    'm2_prices_div_active_items-session_id_by_prices_median-v2',
    'm2_price_rank',
    'm2_act_pre1',
    'm2_lastest_item-impr_rank',
    'm2_impr_rank_sub_impressions_by_impr_rank_median',
    'm2_price_div',
    'm2_session_act_sum',
    'm2_prices_div_active_items-session_id_by_prices_median',
    'm2_impressions_by_hist_interaction item info_sum',
    'm2_impressions_by_hist_interaction item image_sum',
    'm2_impressions_by_hist_clickout item_sum',
    'm2_session_id_by_prices_count',
    'm2_impressions_target',
    'm2_impressions_active_ratio',
    'm2_price_div_impr_rank_1_price',
    'm2_impressions_target_sub_session_median',
    'm2_impressions_target_sub_session_max',
    'm2_session_hist_clickout item',
    'm2_device',
    'm2_impr_rank_sub_session_id_by_impr_rank_median',
    'm2_session_hist_interaction item image',
    'm2_impr_rank_1_impressions_target',
    'm2_impr_rank_sub_session_id_by_impr_rank_max',
    'm2_impr_rank_sub_session_id_by_impr_rank_min',
    'm2_current_filters',
    'item_id_impression_prev_item_meta_cos',
    'item_id_impression_prev_co_appearence_interaction_count',
    'item_id_impression_prev_co_appearence_impression_count',
    'item_id_impression_prev_similarity_wv_impression',
    'item_id_impression_prev_similarity_wv_interaction',
    'item_id_impression_first_item_meta_cos',
    'item_id_impression_first_co_appearence_interaction_count',
    'item_id_impression_first_co_appearence_impression_count',
    'item_id_impression_first_similarity_wv_impression',
    'item_id_impression_first_similarity_wv_interaction',
    'item_id_interaction_last_item_meta_cos',
    'item_id_interaction_last_co_appearence_interaction_count',
    'item_id_interaction_last_co_appearence_impression_count',
    'item_id_interaction_last_similarity_wv_impression',
    'item_id_interaction_last_similarity_wv_interaction',
    'item_id_interaction_most_item_meta_cos',
    'item_id_interaction_most_co_appearence_interaction_count',
    'item_id_interaction_most_co_appearence_impression_count',
    'item_id_interaction_most_similarity_wv_impression',
    'item_id_interaction_most_similarity_wv_interaction',
    'item_id_interaction_last_similarity_wv_impression_rank',
    'item_id_impression_prev_item_meta_cos_rank',
    'item_id_impression_prev_co_appearence_impression_count_rank',
    'item_id_impression_first_co_appearence_interaction_count_rank',
    'item_id_impression_first_co_appearence_impression_count_rank',
    'item_id_interaction_last_co_appearence_impression_count_rank',
    'item_id_interaction_last_co_appearence_interaction_count_rank',
    'item_id_impression_prev_price_div',
    'item_id_impression_prev_price_rank_div',
    'item_id_impression_prev_item_rank_div',
    'item_id_impression_prev_session_item_interaction_count_div',
    'item_id_impression_first_price_div',
    'item_id_impression_first_price_rank_div',
    'item_id_impression_first_item_rank_div',
    'item_id_impression_first_session_item_interaction_count_div',
    'item_id_interaction_last_price_div',
    'item_id_interaction_last_price_rank_div',
    'item_id_interaction_last_item_rank_div',
    'item_id_interaction_last_session_item_interaction_count_div',
    'item_id_interaction_most_price_div',
    'item_id_interaction_most_price_rank_div',
    'item_id_interaction_most_item_rank_div',
    'item_id_interaction_most_session_item_interaction_count_div',
    'item_id_impression_prev_item_win_ratio',
    'item_id_impression_first_item_win_ratio',
    'item_id_interaction_last_item_win_ratio',
    'item_id_interaction_most_item_win_ratio',
    'item_id_impression_prev_item_win_ratio_rank',
    'item_id_impression_first_item_win_ratio_rank',
    'item_id_interaction_last_item_win_ratio_rank',
    'item_id_interaction_most_item_win_ratio_rank'
]